language: scala

dist: trusty

scala:
  - 2.12.10
  - 2.13.0
  -
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier